package uk.anbu.devnotes.controller;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import uk.anbu.devnotes.service.EditLockService;

/**
 * Provides REST endpoints for the client-side edit-lock mechanism.
 *
 * <ul>
 *   <li>{@code POST /edit-lock/acquire}   - try to take an exclusive lock</li>
 *   <li>{@code POST /edit-lock/heartbeat} - keep an active lock alive</li>
 *   <li>{@code POST /edit-lock/release}   - voluntarily give up the lock</li>
 * </ul>
 *
 * All endpoints return a simple JSON body so the JavaScript caller can
 * branch without parsing HTML.
 */
@Slf4j
@RequiredArgsConstructor
@RestController
public class EditLockController {

    private final EditLockService editLockService;

    /**
     * Attempt to acquire an exclusive edit lock for a markdown file.
     *
     * @param filename  relative path of the file (as used elsewhere in the app)
     * @param lockToken unique opaque token generated by the requesting browser session
     * @param force     when {@code true} any existing lock is released before acquiring -
     *                  allows the user to explicitly take over an apparently abandoned session
     * @return {@code {"acquired":true}} on success or {@code {"acquired":false}} when
     *         another live session holds the lock and {@code force} is {@code false}
     */
    @PostMapping("/edit-lock/acquire")
    public ResponseEntity<AcquireResult> acquire(
            @RequestParam String filename,
            @RequestParam String lockToken,
            @RequestParam(defaultValue = "false") boolean force) {

        if (filename == null || filename.isBlank() || lockToken == null || lockToken.isBlank()) {
            return ResponseEntity.badRequest().build();
        }

        var acquired = editLockService.tryAcquireLock(filename, lockToken, force);
        return ResponseEntity.ok(new AcquireResult(acquired));
    }

    /**
     * Refresh the heartbeat timestamp for a held lock.
     *
     * @return {@code {"alive":true}} when the heartbeat was accepted;
     *         {@code {"alive":false}} when the token no longer matches (lock lost or expired)
     */
    @PostMapping("/edit-lock/heartbeat")
    public ResponseEntity<HeartbeatResult> heartbeat(
            @RequestParam String filename,
            @RequestParam String lockToken) {

        if (filename == null || filename.isBlank() || lockToken == null || lockToken.isBlank()) {
            return ResponseEntity.badRequest().build();
        }

        var alive = editLockService.heartbeat(filename, lockToken);
        return ResponseEntity.ok(new HeartbeatResult(alive));
    }

    /**
     * Voluntarily release a held lock.  Silently ignored if the token does not match.
     */
    @PostMapping("/edit-lock/release")
    public ResponseEntity<Void> release(
            @RequestParam String filename,
            @RequestParam String lockToken) {

        if (filename != null && !filename.isBlank() && lockToken != null && !lockToken.isBlank()) {
            editLockService.releaseLock(filename, lockToken);
        }
        return ResponseEntity.ok().build();
    }

    public record AcquireResult(boolean acquired) {}
    public record HeartbeatResult(boolean alive) {}
}