package uk.anbu.devnotes.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Tracks which markdown files are currently open for editing.
 * Each open editor holds a unique lockToken and must send periodic heartbeats.
 * Locks that have not received a heartbeat within LOCK_TIMEOUT are considered stale
 * and will be automatically released on the next acquire/heartbeat/check call.
 */
@Slf4j
@Service
public class EditLockService {

    /** Locks older than this without a heartbeat are considered expired. */
    static final Duration LOCK_TIMEOUT = Duration.ofSeconds(60);

    record EditLock(String lockToken, Instant lastHeartbeat) {
        boolean isExpired() {
            return Instant.now().isAfter(lastHeartbeat.plus(LOCK_TIMEOUT));
        }
    }

    private final ConcurrentHashMap<String, EditLock> locks = new ConcurrentHashMap<>();

    /**
     * Attempt to acquire an exclusive edit lock for {@code filename}.
     *
     * @param filename  relative path of the markdown file
     * @param lockToken unique token generated by the client for this editor session
     * @param force     when {@code true} any existing lock (even from a different token) is
     *                  released before attempting acquisition
     * @return {@code true} if the lock was acquired (or already held by the same token);
     *         {@code false} if the file is currently locked by a different, live token
     */
    public boolean tryAcquireLock(String filename, String lockToken, boolean force) {
        if (force) {
            locks.remove(filename);
            log.info("Edit lock for '{}' force-released by token {}", filename, lockToken);
        }

        // Purge expired lock so a stale lock never blocks a new editor
        locks.compute(filename, (key, existing) -> {
            if (existing != null && existing.isExpired()) {
                log.info("Edit lock for '{}' expired (token {}), releasing", filename, existing.lockToken());
                return null;
            }
            return existing;
        });

        var result = new boolean[]{false};
        locks.compute(filename, (key, existing) -> {
            if (existing == null) {
                // No lock held → acquire it
                result[0] = true;
                return new EditLock(lockToken, Instant.now());
            }
            if (existing.lockToken().equals(lockToken)) {
                // Same token → refresh heartbeat
                result[0] = true;
                return new EditLock(lockToken, Instant.now());
            }
            // Locked by a different token - leave lock unchanged
            return existing;
        });

        if (result[0]) {
            log.debug("Edit lock acquired for '{}' (token {})", filename, lockToken);
        } else {
            log.info("Edit lock for '{}' denied - already held by another session", filename);
        }
        return result[0];
    }


    /**
     * Refresh the heartbeat timestamp for an existing lock.
     *
     * @return {@code true} if the heartbeat was accepted; {@code false} if the token does not
     *         match the current lock owner (or no lock exists)
     */
    public boolean heartbeat(String filename, String lockToken) {
        var result = new boolean[]{false};
        locks.compute(filename, (key, existing) -> {
            if (existing == null) {
                return null;
            }
            if (existing.isExpired()) {
                log.info("Heartbeat received for expired lock on '{}' (token {})", filename, existing.lockToken());
                return null;
            }
            if (existing.lockToken().equals(lockToken)) {
                result[0] = true;
                return new EditLock(lockToken, Instant.now());
            }
            return existing;
        });
        return result[0];
    }

    /**
     * Release the edit lock if the supplied token matches the current owner.
     */
    public void releaseLock(String filename, String lockToken) {
        locks.compute(filename, (key, existing) -> {
            if (existing != null && existing.lockToken().equals(lockToken)) {
                log.info("Edit lock released for '{}' (token {})", filename, lockToken);
                return null;
            }
            return existing;
        });
    }
}