spring.application.name: devtools

devtools.docsDirectory: @user.home@/docs

# jte configuration
gg.jte:
  templateLocation:
    @project.basedir@/src/main/resources/templates/

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: prod
gg.jte:
  usePrecompiledTemplates: true

---
spring:
  config:
    activate:
      on-profile: dev

gg.jte.developmentMode: true