spring.application.name: devnotes

spring.profiles.active: prod

logging:
  level:
    uk.anbu.devnotes: DEBUG

devnotes:
  docsDirectory: @user.home@/docs
  allowedIps: 127.0.0.1,0:0:0:0:0:0:0:1,192.168.1.103
  sshKeyFile:
  chromeDriverLocation:
  sql.maxRows: 1000

# jte configuration
gg.jte:
  templateLocation:
    @project.basedir@/src/main/resources/templates/

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

server:
  port: 8443
  ssl:
    enabled: true
    bundle: localtls   # name of the bundle to use

spring.ssl.bundle.pem.localtls:
  reload-on-update: true    # optional hot reload
  keystore:
    certificate: "tls/localtls.crt"
    private-key: "tls/localtls.key"

---
spring.config.activate.on-profile: prod
gg.jte:
  usePrecompiledTemplates: true
  templateLocation: classpath:templates/

---
spring.config.activate.on-profile: dev
gg.jte:
  templateLocation: src/main/jte/

gg.jte.developmentMode: true