spring.application.name: devtools

spring.profiles.active: default

devtools:
  docsDirectory: @user.home@/docs
  sshKeyFile:

# jte configuration
gg.jte:
  templateLocation:
    @project.basedir@/src/main/resources/templates/

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

---
spring.config.activate.on-profile: prod
gg.jte:
  usePrecompiledTemplates: true
  templateLocation: classpath:templates/

---
spring.config.activate.on-profile: dev
gg.jte:
  templateLocation: src/main/jte/

gg.jte.developmentMode: true