<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <style>
        [x-cloak] {
            display: none !important;
        }
    </style>
    <title>Tools</title>
</head>
<body class="p-8">
<h1>Tools</h1>

Pomodoro Timer
<a href="/pomodoro">/pomodoro</a><br>

Awesome bar
<a href="/awesome-bar">/awesome-bar</a><br>

Base64 Encoder
<a href="/base64">/base64</a><br>

Database Metadata Fetcher
<a href="/database">/database</a>
<br>

Config editor
<a href="/config">/config</a>
<br>

Script Scheduler
<a href="/scheduler">/scheduler</a>
<br>

</body>
</html>