<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <title>Tools</title>
</head>
<body class="p-8">
<h1>Tools</h1>

<div class="tools-list">
    <a href="/pomodoro" class="btn-blue-glow"><i class="fas fa-clock"></i>Pomodoro Timer</a>
    <a href="/awesome-bar" class="btn-blue-glow"><i class="fas fa-bolt"></i>Awesome Bar</a>
    <a href="/base64" class="btn-blue-glow"><i class="fas fa-code"></i>Base64 Encoder</a>
    <a href="/database" class="btn-blue-glow"><i class="fas fa-database"></i>Database Metadata Fetcher</a>
    <a href="/config" class="btn-blue-glow"><i class="fas fa-cog"></i>Config Editor</a>
    <a href="/scheduler" class="btn-blue-glow"><i class="fas fa-calendar-alt"></i>Script Scheduler</a>
    <a href="/flashcards" class="btn-blue-glow"><i class="fas fa-layer-group"></i>Flash Cards</a>
    <a href="/tools/exchange-rates" class="btn-blue-glow"><i class="fas fa-dollar-sign"></i>Exchange Rates</a>
    <a href="/tools/image-audit" class="btn-blue-glow"><i class="fas fa-images"></i>Image Audit</a>
    <a href="/mermaid-playground" class="btn-blue-glow"><i class="fas fa-project-diagram"></i>Mermaid Playground</a>
    <a href="/groovy-playground" class="btn-blue-glow"><i class="fas fa-terminal"></i>Groovy Playground</a>
</div>
<hr>
<a href="/" class="btn-blue-glow"><i class="fas fa-home"></i>Home</a>

</body>
</html>