<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <title>Tools</title>
</head>
<body class="p-8">
<h1>Tools</h1>

<div class="tools-list">
    <a href="/pomodoro" class="btn-blue-glow"><i class="fas fa-clock"></i>Pomodoro Timer</a>
    <a href="/awesome-bar" class="btn-blue-glow"><i class="fas fa-bolt"></i>Awesome Bar</a>
    <a href="/base64" class="btn-blue-glow"><i class="fas fa-code"></i>Base64 Encoder</a>
    <a href="/database" class="btn-blue-glow"><i class="fas fa-database"></i>Database Metadata Fetcher</a>
    <a href="/config" class="btn-blue-glow"><i class="fas fa-cog"></i>Config Editor</a>
    <a href="/scheduler" class="btn-blue-glow"><i class="fas fa-calendar-alt"></i>Script Scheduler</a>
</div>
<hr>
<a href="/" class="btn-blue-glow"><i class="fas fa-home"></i>Home</a>

</body>
</html>