GET http://localhost:8080/groovyToText

"Hello World"

###
POST http://localhost:8080/addFleetingItem
Content-Type: application/text

"yet another item"

###
GET http://localhost:8080/search?q=TODO&json=true,caseSensitive=true
